name: Example Usage

on:
  workflow_dispatch:
    inputs:
      safe-address:
        description: 'Safe multisig address'
        required: true
        type: string
      rpc-url:
        description: 'RPC URL'
        required: true
        type: string
      script-path:
        description: 'Foundry script path'
        required: true
        default: 'script/SafeOperations.s.sol'
        type: string
      dry-run:
        description: 'Dry run mode'
        required: false
        default: true
        type: boolean

jobs:
  safe-operation:
    runs-on: ubuntu-latest
    name: Safe Multisig Operation
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute Safe Operation
        id: safe-op
        uses: ./
        with:
          safe-address: ${{ inputs.safe-address }}
          rpc-url: ${{ inputs.rpc-url }}
          proposer-private-key: ${{ secrets.PROPOSER_PRIVATE_KEY }}
          safe-api-key: ${{ secrets.SAFE_API_KEY }}
          foundry-script-path: ${{ inputs.script-path }}
          dry-run: ${{ inputs.dry-run }}

      - name: Display Results
        run: |
          echo "Operation Status: ${{ steps.safe-op.outputs.status }}"
          echo "Transaction Count: ${{ steps.safe-op.outputs.transaction-count }}"
          echo "Transaction Hash: ${{ steps.safe-op.outputs.transaction-hash }}"
          echo "All Transaction Hashes: ${{ steps.safe-op.outputs.transaction-hashes }}"
