name: Test Action

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test Safe Transaction Proposer Action
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build action
        run: npm run build:action

      - name: Setup test environment
        run: |
          # Ensure test broadcast directory exists
          mkdir -p broadcast/Test.s.sol/1
          
          # Verify test files are in place
          if [ ! -f "script/Test.s.sol" ]; then
            echo "ERROR: Test script not found"
            exit 1
          fi
          
          if [ ! -f "broadcast/Test.s.sol/1/run-1692000000.json" ]; then
            echo "ERROR: Test broadcast file not found"
            exit 1
          fi
          
          echo "Test environment setup complete"

      - name: Test action build
        run: |
          if [ ! -f "dist/action/index.js" ]; then
            echo "Action build failed - index.js not found"
            exit 1
          fi
          echo "Action build successful"

      # Test with minimal required inputs (dry run)
      # This test uses a mock broadcast file for testing the action without requiring actual Foundry execution
      - name: Test Action - Dry Run with Mock Broadcast
        uses: ./
        with:
          safe-address: '0x0000000000000000000000000000000000000000'
          rpc-url: 'https://eth.llamarpc.com'
          proposer-private-key: ${{ secrets.TEST_PRIVATE_KEY || '0x0000000000000000000000000000000000000000000000000000000000000001' }}
          safe-api-key: 'test-key'
          foundry-script-path: 'script/Test.s.sol:Test'
          dry-run: true
      
      # Test that the action fails gracefully with invalid inputs
      - name: Test Action - Invalid Script Path (Expected to Fail)
        continue-on-error: true
        id: test-invalid
        uses: ./
        with:
          safe-address: '0x0000000000000000000000000000000000000000'
          rpc-url: 'https://eth.llamarpc.com'
          proposer-private-key: ${{ secrets.TEST_PRIVATE_KEY || '0x0000000000000000000000000000000000000000000000000000000000000001' }}
          safe-api-key: 'test-key'
          foundry-script-path: 'script/NonExistent.s.sol:NonExistent'
          dry-run: true
      
      - name: Verify Invalid Test Failed as Expected
        run: |
          if [ "${{ steps.test-invalid.outcome }}" = "success" ]; then
            echo "ERROR: Invalid test should have failed but succeeded"
            exit 1
          else
            echo "SUCCESS: Invalid test failed as expected"
          fi

  lint:
    runs-on: ubuntu-latest
    name: Lint TypeScript

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript compiler
        run: npm run typecheck

      - name: Run linter
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    name: Build Package

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Build action
        run: npm run build:action
